version: '3.1'

services:
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        environment:
            MONGO_USERNAME: root
            MONGO_PASSWORD: root
            MONGO_URL: mongodb://localhost:27017/products
        volumes:
            - ./docker/mongo/mongod.conf:/etc/mongod.conf
            - ./docker/mongo/initdb.d/:/docker-entrypoint-initdb.d/
            - ./docker/mongo/data/db/:/data/db/
            - ./docker/mongo/data/log/:/var/log/mongodb/
        ports:
            - "27017:27017"
        command: ["-f", "/etc/mongod.conf"]

    elasticsearch:
        image: elasticsearch:7.14.0
        container_name: elasticsearch
        environment:
        - xpack.security.enabled=false
        - discovery.type=single-node
        ulimits:
        memlock:
            soft: -1
            hard: -1
        nofile:
            soft: 65536
            hard: 65536
        cap_add:
        - IPC_LOCK
        volumes:
        - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
        ports:
        - 9200:9200
        - 9300:9300